# newest version docker 
version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
    hostname: client
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - example-net  
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
    hostname: backend
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - example-net
    environment:
      - URL_MONGO_DB=mongodb://mongo/nest
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
networks:
  example-net:
    external: true
volumes:
  mongodb_data: