# newest version docker 
version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
    hostname: client
    ports:
      - 80:80
    volumes:
      - ./client/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - example-net  
networks:
  example-net:
    external: true